name: CI

on:
  push:
    branches: [ main, develop, v1.0.2 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3, 8.4]

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql
        coverage: xdebug

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run PHPUnit Tests
      run: composer test

    - name: Run PHPStan Analysis
      run: composer phpstan

    - name: Check PSR-12 Compliance
      run: composer cs:check

    - name: Generate Coverage Report
      if: matrix.php-version == '8.4'
      run: composer test-coverage

    - name: Upload coverage to Codecov
      if: matrix.php-version == '8.4'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
